#############################################################################
# Makefile for building: ../../bin/editexpt.app/Contents/MacOS/editexpt
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Sep 12 16:56:21 2012
# Project:  editexpt.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/macx-xcode -o editexpt.xcodeproj/project.pbxproj editexpt.pro
#############################################################################

QMAKE    = /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/bin/qmake
editexpt.xcodeproj/project.pbxproj: editexpt.pro  /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/macx-xcode/qmake.conf /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/mac.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/g++-macx.conf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/debug_and_release.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/x86_64.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/objective_c.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/rez.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/sdk.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/phonon.framework/phonon.prl \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtGui.framework/QtGui.prl \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtCore.framework/QtCore.prl \
		/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtSql.framework/QtSql.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/macx-xcode -o editexpt.xcodeproj/project.pbxproj editexpt.pro
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/mac.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/gcc-base-macx.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/common/g++-macx.conf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/debug_and_release.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/default_post.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/x86_64.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/objective_c.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/rez.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/mac/sdk.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/phonon.framework/phonon.prl:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtGui.framework/QtGui.prl:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtCore.framework/QtCore.prl:
/usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/lib/QtSql.framework/QtSql.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.1-x86_64-no-dbus-dynamic/mkspecs/macx-xcode -o editexpt.xcodeproj/project.pbxproj editexpt.pro

