#!/bin/sh

if [ $# -ne 1 ]; then 
	echo "usage: relocate_habit_for_distribution app_bundle"
	exit -1
fi

# check that dest exists, if not, exit with error
APP=$1
EXECUTABLE_DIR=$APP/Contents/MacOS
GSTREAMER_DIR=$APP/Contents/Frameworks/GStreamer.framework
if [ ! -d $EXECUTABLE_DIR ]; then
	echo "App dir $EXECUTABLE_DIR not found."
	exit 1
fi
if [ ! -d $GSTREAMER_DIR ]; then
	echo "Embedded GStreamer dir $GSTREAMER_DIR not found."
	exit 1
fi

# do relocation for gstreamer stuff
echo "relocating gstreamer framework found at $GSTREAMER_DIR"
osxrelocator -r ${GSTREAMER_DIR} /Library/Frameworks/GStreamer.framework @executable_path/../Frameworks/GStreamer.framework > /dev/null

# not sure if this is needed
install_name_tool -id @executable_path/../Frameworks/GStreamer.framework/GStreamer ${GSTREAMER_DIR}/Versions/Current/GStreamer

# Need this trick so gst-plugin-scanner works with relocated libs
echo "gst-plugin-scanner fix..."
(cd ${GSTREAMER_DIR} && echo "PWD `pwd`" && ln -s ../../../../ Versions/Current/libexec/Frameworks && ls -l Versions/Current/libexec/Frameworks)

# now do relocation on app itself
macdeployqt $APP
osxrelocator -r $EXECUTABLE_DIR /Library/Frameworks/GStreamer.framework @executable_path/../Frameworks/GStreamer.framework > /dev/null
